"""add_scheduled_actions

Revision ID: 3b3b180c3b35
Revises: efadae527519
Create Date: 2026-08-29 21:46:42.019284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b3b180c3b35'
down_revision: Union[str, None] = 'efadae527519'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_actions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.BigInteger(), nullable=False),
    sa.Column('action_type', sa.String(length=32), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='PENDING', nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['recovery_cases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_scheduled_actions_case_id'), 'scheduled_actions', ['case_id'], unique=False)
    op.create_index(op.f('ix_scheduled_actions_scheduled_for'), 'scheduled_actions', ['scheduled_for'], unique=False)
    op.create_index(op.f('ix_scheduled_actions_status'), 'scheduled_actions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scheduled_actions_status'), table_name='scheduled_actions')
    op.drop_index(op.f('ix_scheduled_actions_scheduled_for'), table_name='scheduled_actions')
    op.drop_index(op.f('ix_scheduled_actions_case_id'), table_name='scheduled_actions')
    op.drop_table('scheduled_actions')
    # ### end Alembic commands ###
