"""db_foundation_v2_recovery_attempts_and_lifecycle

Revision ID: efadae527519
Revises: 741dcb481af8
Create Date: 2026-08-28 23:50:47.190066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'efadae527519'
down_revision: Union[str, None] = '741dcb481af8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recovery_attempts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.BigInteger(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('p0_at_decision', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('pa_at_decision', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('expected_net_recovery_at_decision', sa.BigInteger(), nullable=True),
    sa.Column('intervention_cost', sa.Integer(), nullable=True),
    sa.Column('policy_decision', sa.String(length=16), nullable=False),
    sa.Column('policy_reason', sa.Text(), nullable=True),
    sa.Column('execution_status', sa.String(length=16), server_default='PENDING', nullable=False),
    sa.Column('razorpay_reference', sa.String(length=64), nullable=True),
    sa.Column('execution_error', sa.Text(), nullable=True),
    sa.Column('outcome', sa.String(length=16), nullable=True),
    sa.Column('outcome_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('freshness_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('freshness_passed', sa.Boolean(), nullable=True),
    sa.Column('attempted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('orchestrator_trace', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['recovery_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recovery_attempts_action'), 'recovery_attempts', ['action'], unique=False)
    op.create_index(op.f('ix_recovery_attempts_case_id'), 'recovery_attempts', ['case_id'], unique=False)
    op.create_index(op.f('ix_recovery_attempts_outcome'), 'recovery_attempts', ['outcome'], unique=False)
    op.add_column('recovery_cases', sa.Column('attempt_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('recovery_cases', sa.Column('last_action', sa.String(length=32), nullable=True))
    op.add_column('recovery_cases', sa.Column('recommended_action', sa.String(length=32), nullable=True))
    op.add_column('recovery_cases', sa.Column('payment_method', sa.String(length=32), nullable=True))
    op.add_column('recovery_cases', sa.Column('failure_category', sa.String(length=32), nullable=True))
    op.add_column('recovery_cases', sa.Column('recommended_action_pa', sa.Numeric(precision=6, scale=4), nullable=True))
    op.add_column('recovery_cases', sa.Column('stop_reason', sa.Text(), nullable=True))
    op.add_column('recovery_cases', sa.Column('escalation_reason', sa.Text(), nullable=True))
    op.add_column('recovery_cases', sa.Column('next_action_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('recovery_cases', sa.Column('mandate_id', sa.String(length=64), nullable=True))
    op.add_column('recovery_cases', sa.Column('mandate_status', sa.String(length=32), nullable=True))
    op.add_column('recovery_cases', sa.Column('notification_sent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('recovery_cases', sa.Column('next_allowed_debit_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('recovery_cases', sa.Column('retry_budget_remaining', sa.Integer(), nullable=True))
    op.alter_column('recovery_cases', 'status',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=24),
               existing_nullable=False,
               existing_server_default=sa.text("'CREATED'::character varying"))
    op.alter_column('recovery_cases', 'p0',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               type_=sa.Numeric(precision=6, scale=4),
               existing_nullable=True)
    op.alter_column('recovery_cases', 'expected_uplift',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               type_=sa.Numeric(precision=6, scale=4),
               existing_nullable=True)
    op.create_index(op.f('ix_recovery_cases_subscription_id'), 'recovery_cases', ['subscription_id'], unique=False)
    op.drop_column('recovery_cases', 'best_action')
    op.drop_column('recovery_cases', 'best_action_pa')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recovery_cases', sa.Column('best_action_pa', sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=True))
    op.add_column('recovery_cases', sa.Column('best_action', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_recovery_cases_subscription_id'), table_name='recovery_cases')
    op.alter_column('recovery_cases', 'expected_uplift',
               existing_type=sa.Numeric(precision=6, scale=4),
               type_=sa.NUMERIC(precision=5, scale=4),
               existing_nullable=True)
    op.alter_column('recovery_cases', 'p0',
               existing_type=sa.Numeric(precision=6, scale=4),
               type_=sa.NUMERIC(precision=5, scale=4),
               existing_nullable=True)
    op.alter_column('recovery_cases', 'status',
               existing_type=sa.String(length=24),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False,
               existing_server_default=sa.text("'CREATED'::character varying"))
    op.drop_column('recovery_cases', 'retry_budget_remaining')
    op.drop_column('recovery_cases', 'next_allowed_debit_at')
    op.drop_column('recovery_cases', 'notification_sent_at')
    op.drop_column('recovery_cases', 'mandate_status')
    op.drop_column('recovery_cases', 'mandate_id')
    op.drop_column('recovery_cases', 'next_action_at')
    op.drop_column('recovery_cases', 'escalation_reason')
    op.drop_column('recovery_cases', 'stop_reason')
    op.drop_column('recovery_cases', 'recommended_action_pa')
    op.drop_column('recovery_cases', 'failure_category')
    op.drop_column('recovery_cases', 'payment_method')
    op.drop_column('recovery_cases', 'recommended_action')
    op.drop_column('recovery_cases', 'last_action')
    op.drop_column('recovery_cases', 'attempt_count')
    op.drop_index(op.f('ix_recovery_attempts_outcome'), table_name='recovery_attempts')
    op.drop_index(op.f('ix_recovery_attempts_case_id'), table_name='recovery_attempts')
    op.drop_index(op.f('ix_recovery_attempts_action'), table_name='recovery_attempts')
    op.drop_table('recovery_attempts')
    # ### end Alembic commands ###
